# Generated by Django 5.1.4 on 2024-12-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                help_text="Дата производства продукта (записи в БД)",
                null=True,
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
